"""use new model Data

Revision ID: a208876418c0
Revises: fcbc58986f4c
Create Date: 2019-01-19 12:37:12.805201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a208876418c0'
down_revision = 'fcbc58986f4c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_login'], ['users.login'], name=op.f('fk_data_user_login_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
